carts/urls.py
from django.contrib import admin
from django.urls import path
from carts import views


app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:event_slug>/',views.cart_add, name='cart_add'),
    path('cart_change/<slug:event_slug>/',views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
    
]

event_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from event_management.settings import DEBUG

from event_management import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace='main')),
    path('catalog/', include('events.urls', namespace='catalog')),
    path('user/', include('users.urls',namespace='user')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include('carts.urls',namespace='cart')),


    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

events/urls.py
from django.contrib import admin
from django.urls import path
from events import views


app_name = 'events'
urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('event/<slug:event_slug>/',views.about, name='about'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

events/models.py
from django.db import models

import locale

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=150, unique=True )
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    place = models.CharField(max_length=150, unique=True )
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2,verbose_name = 'Цена')
    capacity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True)

    class Meta:
        db_table = 'Event'
        ordering = ("id",)
        
    def __str__(self):
        return self.name
    
    def formatted_start_time(self):
        locale.setlocale(locale.LC_TIME, 'ru_RU.UTF-8')
        formatted_date = self.start_time.strftime('%-d %B %Y')
        locale.setlocale(locale.LC_TIME, '')
        return formatted_date
    
    def sell_price(self):
        return self.price

events/views.py
from django.shortcuts import render,get_list_or_404, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import Event, Categories
from events.utils import q_search

def about(request,event_slug):
    event = Event.objects.get(slug=event_slug)

    context = {
        "event": event,
        "title": event.name,
             
    }

    return render(request, "events/about.html", context)


def catalog(request, category_slug=None):
    page = request.GET.get('page',1)
    order_by = request.GET.get('order_by',None)
    query = request.GET.get('q',None)




    if category_slug == "all":
        events = Event.objects.all().order_by('start_time')
    elif query:
        events = q_search(query)
    else:
        events = get_list_or_404(Event.objects.filter(category__slug=category_slug))


    if order_by and order_by != 'default':
        events = events.order_by(order_by)
    
    paginator = Paginator(events,3)
    current_page = paginator.page(int(page))

    context = {
        "title": "Home - Каталог",
        "events": current_page,
        "slug_url":category_slug,
    }
    return render(request, "events/catalog.html", context)

events/templates/events/about.html
{% extends "home.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="eventcard">
    <div class="info2">
        <div class="img2">
            <img class="event-img2" src="{{ event.image.url }}" />
        </div>
        <div class="text2">
            <div class="event-name2">{{ event.name }}</div>
            <div class="description">
                <p class="desc">описание</p>
                <div class="description-of-event2">{{ event.description }}</div>    
            </div>
            <p class="timee"> время</p>
            <div class="event-time2">{{ event.start_time|date:"H:i" }}</div>
            <div class="event-date">{{ event.formatted_start_time }}</div>
            <p class = "location"> локация</p>
            <div class="event-location">{{ event.place }}</div>
            <div class="button">
                <a href='{% url "cart:cart_add" event.slug %}' class='btn btn-dark add-to-cart'> Добавить в избранное</a>
            </div>
        </div>
    </div>
</div>


{% endblock  %}

events/templates/events/catalog.html
{% extends "home.html" %}
{% load static %}
{% load events_tags %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}


{% block content %}
<li class="dropdown2 ms-2">
    <a href="#" class="dropbtn btn btn-dark">Фильтры</a>
    <div class="dropdown2-content bg-dark p-3">
      <form action="{% if request.get.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %} {% endif %}" method="get" data-bs-theme="dark">
        <div class="form-check text-white">
          <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" >
          {% if request.get.q %}
          <input type="hidden" name="q" value="{{ request.GET.q }}">
          {% endif %}
          <label class="form-check-label" for="flexCheckDefault">
            Товары по акции
          </label>
        </div>
        <p class="text-white mt-3">Сортировать:</p>
        <div class="form-check text-white">
          <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
          {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
          <label class="form-check-label" for="flexRadioDefault1">
            По умолчанию
          </label>
        </div>
        <div class="form-check text-white">
          <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="-capacity" 
          {% if request.GET.order_by == '-capacity' %}checked{% endif %}>
          <label class="form-check-label" for="flexRadioDefault2">
            От больше мест
          </label>
        </div>
        <div class="form-check text-white">
          <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="capacity" 
          {% if request.GET.order_by == 'capacity' %}checked{% endif %}>
          <label class="form-check-label" for="flexRadioDefault3">
            От меньше мест
          </label>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Применить</button>
      </form>
    </div>
  </li>
  <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
</form>
{% if request.GET.q %}
      <h3 class='mt-4'> Результаты поиска по запросу {{request.GET.q}}</h3>
      {% if not events %}
       <h2 class='mt-4'> По запросу ничего не найдено</h2>
      {% endif %}
      {% endif %}
  <div class="events">
    <div class="event-container">
      {% for event in events %}
      <div class="event-item">
        
    </a>
          <a href="{% url "catalog:about" event.slug %}">
            <img class="event-img" src="{{ event.image.url }}" />
            <p class="card-title">
                {% autoescape off %}
                    {% if event.headline %}
                    {{event.headline}}
                    {% else %}
                    {{ event.name }}
                    {% endif %}
                {% endautoescape %}
            </p>
        </a>     
        <p class="event-capacity">
          {% autoescape off %}
          {% if event.bodyline %}
          {{ event.bodyline|truncatechars:100 }}
          {% else %}
          {{ event.description|truncatechars:35 }}
          {% endif %}
          {% endautoescape %}</p>
        <p class="event-date">{{ event.start_time.date }}</p>
        <p class="event-time">{{ event.start_time|date:"H:i" }}</p>
        <p class="event-capacity">{{ event.capacity }}</p>
      </div>
      {% endfor %}
      
    </div>
    </div>
    <nav aria-label="Page navigation example" class="pagination-nav">
        <ul class="pagination justify-content-center my-4">
            <li class="page-item {% if not events.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if events.has_previous %}?{%change_params page=events.previous_page_number%}{% else %}
              #
              {% endif %}
              ">Назад</a>
            </li>
      
            {% for page in events.paginator.page_range %}
            {% if page >= events.number|add:-2 and page <= events.number|add:+2 %}
            <li 
            class="page-item {% if events.number == page %}active{% endif %}">
            <a class="page-link" href="?{%change_params page=page%}">{{page}}</a>
            </li>
            {% endif %}
            {% endfor %}
            
            <li class="page-item {% if not events.has_next %}disabled{% endif %}">
              <a class="page-link" href="{% if events.has_next %}?{%change_params page=events.next_page_number%}{% else %}
              #
              {% endif %}
              ">Следующая</a>
            </li>
        </ul>
      </nav>
  

{%endblock%}