event_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from event_management.settings import DEBUG

from event_management import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace='main')),
    path('catalog/', include('events.urls', namespace='catalog')),
    path('user/', include('users.urls',namespace='user')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include('carts.urls',namespace='cart')),


    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views



app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm,UserChangeForm

from users.models import User
class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username','password']
    
    username = forms.CharField()
    password = forms.CharField()
    

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()



class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from events.models import Event

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm





def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            if user:
                auth.login(request,user)
                messages.success(request, f"(username), Вы вошли в аккаунт")
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    

    context = {
        'title': 'Home - Авторизация',
        'form':form,
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request,user)
            messages.success(request,f"(user.username), вы успешно зарегистрированы и вошли в аккаунт")
            if request.POST.get('next',None):
                return HttpResponseRedirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Home - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST,instance=request.user,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,f"(user.username), вы успешно зарегистрированы и вошли в аккаунт")
            
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'title': 'Home - Кабинет',
        'form':form
    }
    return render(request, 'users/profile.html', context)



def users_cart(request):
    return render(request,'users/users_cart.html')





@login_required
def logout(request):
    messages.success(request,f"(request.user.username), вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "home.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}

<form action="{% url "user:login" %}" method ='post'>
  {% csrf_token %}
  {% if request.GET.next %}
  <input type='hidden' name='next' value={{request.GET.next}}>
  {% endif %}
  {% if form.non_field_errors %}
  <p>{{form.non_field_errors}}</p>
  {% endif %}
  <div class="register">
    <label for="id_username"><b>Имя пользователя</b></label>
    <input type="text" class = "form_control" value = '{% if form.username.value %}{{form.username.value}}{% endif %}'id = 'id_username' placeholder="Введите ваше имя пользователя" name="username" required>

    <label for="id_password"><b>Пароль</b></label>
    <input type="password" class = 'form_control' id = 'id_password'placeholder="Введите ваш пароль" name="password" required>


  {% comment %}
    <div class="register">
      <label for="{{form.username.id_for_label}}"><b>Имя пользователя</b></label>
      {{form.username}}
  
      <label for="{{form.password.id_for_label}}"><b>Пароль</b></label>
      {{form.password}}
  {% endcomment %}


    <!--<div class="register">
      <label for="uname"><b>Имя пользователя</b></label>
      <input type="text" class = "form_control" placeholder="Введите ваше имя пользователя" name="uname" required>
  
      <label for="psw"><b>Пароль</b></label>
      <input type="password" class = 'form_control 'placeholder="Введите ваш пароль" name="psw" required>-->
  
      <button type="submit">Войти</button>
    </div>
  </form>
    <div class="register" style="background-color:#f1f1f1">
      <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>

    </div>
  

{% endblock  %}

<!--<a href="#">Забыли пароль?</a> | <a href="{% url "users:register" %}">Создать аккаунт</a>

users/templates/users/logout.html
{% extends "home.html" %}
{% load static %}

users/templates/users/profile.html
{% extends "home.html" %}
{% load static %}

{% load carts_tag %}
{% block content %}

        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row">
                                <!-- Профиль с данными пользователя -->
                                <div class="col-md-5">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                                        <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12 mb-3 text-center">
                                                    {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/img/darkknight.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_first_name" class="form-label">Имя*</label>
                                                    <input type="text" class="form-control" id="id_first_name"
                                                        name="first_name"
                                                        placeholder="Введите ваше имя"
                                                        value="{{ form.first_name.value }}"
                                                        required>
                                                        {% if form.first_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                                    <input type="text" class="form-control" id="id_last_name" name='last_name'
                                                        placeholder="Введите вашу фамилию" value="{{form.last_name.value}}" required>
                                                        {% if form.last_name.errors %}
                                                        <div class = 'alert alert-danger alert-dismissible fade show'>{{form.last_name.errors}}</div>
                                                        {% endif %}   
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                                    <input type="text" class="form-control" id="id_username"name='username'
                                                        placeholder="Введите ваше имя пользователя" value="{{form.username.value}}" required>
                                                        {% if form.username.errors %}
                                                        <div class = 'alert alert-danger alert-dismissible fade show'>{{form.username.errors}}</div>
                                                        {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="id_email" class="form-label">Email*</label>
                                                    <input type="email" class="form-control" id="id_email"
                                                        name="email"
                                                        placeholder="Введите ваш email *youremail@example.com"
                                                        value="{{ form.email.value }}"
                                                        required>
                                                        {% if form.email.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                        {% endif %}
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-dark">Сохранить</button>
                                        </form>
                                    </div>
                                </div>
            <!-- Корзина -->

            {% user_carts request as carts%}
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                    {% if carts %}
                    <a class="btn btn-dark" href="../orders/create_order.html">
                        Оформить заказ
                    </a>
                    {% endif %}
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                    <td>1</td>
                                                    <td>255.00 $</td>
                                                    <td>255.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Итого:</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стул офисный</a></td>
                                                    <td>2</td>
                                                    <td>30.00 $</td>
                                                    <td>60.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock  %}

users/templates/users/register.html
{% extends "home.html" %}
{% load static %}


{% block register %}
<form action="action_page.php">
    <div class="register">
      <h1>Регистрация</h1>
      <p>Пожалуйста, заполните эту форму, чтобы создать учетную запись.</p>
      <hr>
  
      <label for="email"><b>Электронная почта</b></label>
      <input type="text" placeholder="Введите адрес электронной почты" name="email" id="email" required>
  
      <label for="psw"><b>Пароль</b></label>
      <input type="password" placeholder="Введите пароль" name="psw" id="psw" required>
  
      <label for="psw-repeat"><b>Повторите пароль</b></label>
      <input type="password" placeholder="Повторите пароль" name="psw-repeat" id="psw-repeat" required>
      <hr>
  
      <button type="submit" class="registerbtn">Зарегистрироваться</button>
    </div>
  
    <div class="register signin">
      <p>У вас уже есть аккаунт? <a href="{% url "users:login"%}">Войти</a>.</p>
    </div>
  </form>
  {% endblock %}

users/templates/users/registration.html
{% extends "home.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<form action="{% url "user:registration" %}" method = 'POST'>
    {% csrf_token %}
    <div class="register">
      <h1>Регистрация</h1>
      <p>Пожалуйста, заполните эту форму, чтобы создать учетную запись.</p>
      <hr>
      <div>
      <label for="id_first_name"><b>Имя</b></label>
      <input type="text" class = "form_control" placeholder="Введите ваше имя" name="first_name" id="id_first_name" 
      value='{% if form.first_name.value %}{{form.first_name.value}}{% endif %}' name = 'first_name' required>
      {% if form.first_name.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.first_name.errors}}</div>
      {% endif %}
      </div>
      
      <div>
      <label for="id_last_name"><b>Фамилия</b></label>
      <input type="text" class = "form_control" placeholder="Введите вашу фамилию"
      value='{% if form.last_name.value %}{{form.last_name.value}}{% endif %}'
      name="last_name" id="id_lastname"required>
      {% if form.last_name.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.last_name.errors}}</div>
      {% endif %}
      </div>

      <div>
      <label for="username"><b>Имя пользователя</b></label>
      <input type="text" class = "form_control" placeholder="Введите ваше имя пользователя"
      value='{% if form.username.value %}{{form.username.value}}{% endif %}'
      name="username" id="id_username" required>
      {% if form.username.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.username.errors}}</div>
      {% endif %}  
      </div>

      <div>
      <label for="email"><b>Электронная почта</b></label>
      <input type="email" class = "form_control" placeholder="Введите адрес электронной почты"
      value='{% if form.email.value %}{{form.email.value}}{% endif %}'
      name="email" id="id_email" required>
      {% if form.email.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.email.errors}}</div>
      {% endif %}
      </div>
  
      <div>
      <label for="password1"><b>Пароль</b></label>
      <input type="password" class = "form_control" placeholder="Введите пароль" 
      value='{% if form.password1.value %}{{form.password1.value}}{% endif %}'
      name="password1" id="id_password1" required>
      {% if form.password1.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.password1.errors}}</div>
      {% endif %}  
      </div>

      <div>
      <label for="password2"><b>Повторите пароль</b></label>
      <input type="password" class = "form_control" placeholder="Повторите пароль" 
      value='{% if form.password2.value %}{{form.password2.value}}{% endif %}'
      name="password2" id="id_password2" required>
      {% if form.password2.errors %}
      <div class = 'alert alert-danger alert-dismissible fade show'>{{form.password2.errors}}</div>
      {% endif %}  
      </div>
      <hr>
  
      <button type="submit" class = "form_control" class="registerbtn" >Зарегистрироваться</button>
    </div>
  
    <div class="register signin">
      <p>У вас уже есть аккаунт? <a href="{% url "users:login"%}">Войти</a>.</p>
    </div>
  </form>
  
  {% endblock %}

users/templates/users/users_cart.html
{% extends "home.html" %}
{% load static %}

{% load carts_tag %}

{% block content %}

{% user_carts request as carts%}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
                {% if carts %}
                <a class="btn btn-dark" href="../orders/create_order.html">
                    Оформить заказ
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock  %}