event_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from event_management.settings import DEBUG

from event_management import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace='main')),
    path('catalog/', include('events.urls', namespace='catalog')),
    path('user/', include('users.urls',namespace='user')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include('carts.urls',namespace='cart')),


    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views



app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),

]

templates/home.html
{% load static %}
{% load events_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'deps/css/home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
    <title>{{ title }}</title>
  </head>
  <body>
    <div class="top">
      <nav>
        <ul>
          <li><a href="{% url 'main:index' %}">Главная</a></li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url "user:users_cart" %}">Избранное</a>
          </li>
          {% if not user.is_authenticated %}
          <li class="login"><a href="{% url 'user:login' %}">Войти</a></li>
          {% else %}
          <li class="dropdown">
            <a>{{ user.username }}</a>
            <a href="{% url 'user:profile' %}">Мой профиль</a>
            <div class="dropdown-content">
              <a href="{% url 'user:profile' %}">Личный кабинет</a>
              {% if user.is_admin or user.is_staff %}
              <a href="/admin/">Админ панель</a>
              {% endif %}
              <a href="{% url 'user:logout' %}">Выйти</a>
            </div>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div class="merop">
      <h1>Мероприятия в Астане</h1>
    </div>
    <!-- Значек корзины, вызывает модальное окно -->
{% block modal_cart %}{% endblock  %}
    <!-- Закончилась разметка модального окна -->
    <div class="dropdown mb-2">
      <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Каталог
      </button>
      <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
        {% tag_categories as categories %}
        {% for category in categories %}
        <li><a class="dropdown-item text-white" href="{% url 'catalog:index' category.slug %}">{{ category.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
    <!-- Pagination -->
    {% block content %}{% endblock %}
    <!-- Footer -->
    <footer class="py-4 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Nursat Seitov</p>
      </div>
    </footer>
  </body>
</html>